version: "3.2"

services:
  apache:
    restart: "no"
    image: php:7.4-apache
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/

  mysql:
    restart: "no"
    image: mariadb:${MYSQL_VERSION:-latest}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"

